# Generated by Django 4.0.2 on 2022-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academicien',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=6, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('id_academicien', models.IntegerField()),
                ('id_motif', models.IntegerField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddConstraint(
            model_name='payement',
            constraint=models.UniqueConstraint(fields=('date', 'id_academicien', 'id_motif'), name='uniqueKey'),
        ),
    ]
