# Generated by Django 4.0.2 on 2022-02-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_academicien_id_alter_motif_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicien',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
