# Generated by Django 4.0.2 on 2022-02-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payement_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payement',
            name='heure',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
