# Generated by Django 4.0.2 on 2022-02-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=120, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_academicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_acad', to='api.academicien')),
                ('id_motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_acad', to='api.motif')),
            ],
        ),
        migrations.AddField(
            model_name='motif',
            name='lien',
            field=models.ManyToManyField(blank=True, related_name='paiement', through='api.Payement', to='api.Academicien', verbose_name='Lien'),
        ),
        migrations.AddConstraint(
            model_name='payement',
            constraint=models.UniqueConstraint(fields=('date', 'id_academicien', 'id_motif'), name='uniqueKey'),
        ),
    ]
